language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2048m'" >> ~/.mavenrc
notifications:
  email:
    recipients:
    - my.gama.bot@gmail.com
    on_success: change
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"
addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts:
      - 51.255.46.42
script: 
- bash ./travis/compile.sh		
after_success:
- bash ./travis/validate_and_test.sh	
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export SSHPASS=$USER_PWD 
- bash ./travis/publish.sh
branches:
  only:
    - master
