# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Github Travis

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ GAMA_1.8.2 ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # For manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Adopt OpenJDK 15
        uses: actions/setup-java@v2 
        with:
          distribution: 'adopt-openj9'
          java-version: '15'
          java-package: jdk  

      - name: Prepare build
        run: |
          echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2048m'" >> ~/.mavenrc
          sudo chmod +x $GITHUB_WORKSPACE/travis/*.sh

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        shell: bash
        run: $GITHUB_WORKSPACE/travis/compile.sh 
        env:
          MSG: ${ github.event.head_commit.message }
          
      - name: Validate and test Maven
        shell: bash
        run: $GITHUB_WORKSPACE/travis/validate_and_test.sh
        env:
          MSG: ${ github.event.head_commit.message }

      - name: Set Travis env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
             echo "[WARNING] Forcing travis version release"
             echo "TRAVIS_MSG=ci release" >> $GITHUB_ENV
          else
             echo "TRAVIS_MSG=$(echo $github.event.head_commit.message )" >> $GITHUB_ENV
          fi
          echo $TRAVIS_MSG

      - name: Publish to Github
        shell: bash
        run: $GITHUB_WORKSPACE/travis/publish.sh
        env:  
          SSH_USER_PWD: ${{ secrets.USER_PWD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          MSG: ${{ env.TRAVIS_MSG }}
          GITHUB_TOKEN: ${{ github.token }}
          SSHPASS: ${{ secrets.USER_PWD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TRAVIS_COMMIT: ${ GITHUB_SHA }
          TRAVIS_EVENT_TYPE: ${{ github.event_name }}
