# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Documentation Auto Refresh

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # For manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: GAMA_1.8.2
      
      - name: Set up Adopt OpenJDK 17
        uses: actions/setup-java@v2 
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Prepare build
        run: |
          echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2048m'" >> ~/.mavenrc
          sudo chmod +x $GITHUB_WORKSPACE/travis/*.sh
      
      - name: Build with Maven
        shell: bash
        run: $GITHUB_WORKSPACE/travis/compile.sh 
        env:
          MSG: "ci docs"

      - name: Check if should release version
        run: ./travis/publish.sh
        env:  
          SSH_USER_PWD: ${{ secrets.USER_PWD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          MSG: "ci docs"
          GITHUB_TOKEN: ${{ github.token }}
          SSHPASS: ${{ secrets.USER_PWD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TRAVIS_COMMIT: ${ GITHUB_SHA }
          TRAVIS_EVENT_TYPE: ${{ github.event_name }}
          thePATH: "${{ github.workspace }}/Gama1.7"
      