name: Auto publish release to external stores

on:
  workflow_call:
    inputs:
      tag:
        description: "The tag of the release to publish"
        type: string
        required: true
    secrets:
      BOT_TOKEN:
        required: true
        description: "The token used to authenticate to the Github API"
  
  workflow_dispatch:
      inputs:
        tag:
          description: "The tag of the release to publish"
          type: string
          required: true


run-name: Auto publishing ${{ inputs.tag }} to external stores

jobs:
  get-tag-info: 
    runs-on: ubuntu-latest
    name: Get tag info ğŸ·ï¸

    outputs:
      tag: ${{ steps.release_data.outputs.tag_name }}
      prerelease: ${{ steps.release_data.outputs.prerelease }}

    steps:
      - name: git-get-release-action
        uses: cardinalby/git-get-release-action@1.2.4
        id: release_data
        with:
          tag: ${{ inputs.tag }}

  windows:
    needs: get-tag-info
    runs-on: ubuntu-latest
    name: Publish to windows ğŸªŸ

    steps:
      - name: Publish Gama to Winget ğŸš€
        if: needs.get-tag-info.outputs.prerelease == false
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: GamaPlatform.Gama
          version: ${{ inputs.tag }}
          release-tag: ${{ inputs.tag }}
          installers-regex: \.exe$ # All Exe's
          token: ${{ secrets.BOT_TOKEN }}

      - name: Publish Pre release to Winget ğŸ‘·
        if: needs.get-tag-info.outputs.prerelease == true
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: GamaPlatform.GamaUnstable
          version: ${{ inputs.tag }}
          release-tag: ${{ inputs.tag }}
          installers-regex: \.exe$ # All Exe's
          token: ${{ secrets.BOT_TOKEN }}
          max-versions-to-keep: 1


  docker:
    needs: get-tag-info
    runs-on: ubuntu-latest
    name: Publish pre-release as container ğŸ³
    if: needs.get-tag-info.outputs.prerelease == true

    steps:
      - name: Publish Gama to Github Packages ğŸš€
        run: |
          curl --request POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            --data '{"event_type": "automated-generation"}' \
            https://api.github.com/repos/gama-platform/gama.docker/dispatches 


  linux-debian:
    needs: get-tag-info
    runs-on: ubuntu-latest
    name: Publish to PPA/Debian repo ğŸ§ ğŸŸ ğŸ”´ 

    steps:
      - name: Publish Gama to https://ppa.gama-platform.org ğŸš€
        run: |
          curl -L \
            --request POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --data '{"ref": "main", "inputs": {"tag": "${{ inputs.tag }}"}}' \
            https://api.github.com/repos/gama-platform/gama.ppa/actions/workflows/publish/dispatches


  # linux-arch:
  #   needs: get-tag-info
  #   runs-on: ubuntu-latest
  #   name: Publish to AUR ğŸ§ ğŸ”·

  # macos:
  #   needs: get-tag-info
  #   runs-on: ubuntu-latest
  #   name: Publish to macos ğŸ
